
import { Righteous, Urbanist } from "next/font/google";
import "./globals.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";

const righteous = Righteous({
   weight: "400",
   variable: "--font-righteous",
   subsets: ["latin"],
   display: "swap",
});

const urbanist = Urbanist({
   weight: ["400", "500", "600"],
   variable: "--font-urbanist",
   subsets: ["latin"],
   display: "swap",
});

export const metadata = {
   title: "Coffee Shop | Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {

   return (
      <html lang="en">
         <body className={`body ${righteous.variable} ${urbanist.variable}`}>
            <div className="wrapper">
               <Header />
               {children}
               <Footer />
            </div>
         </body>
      </html>
   );
}
